version: "3.7"
services:
  influxdb:
    image: influxdb
    restart: "unless-stopped"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=hoplin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=hoplinspace
      - DOCKER_INFLUXDB_INIT_BUCKET=DHT11-Measurement
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="influx-admin-token"
